=head1 INTRODUCTION

Some Munin plugins I've written.  See the project
L<http://munin.projects.linpro.no/> for details of what
that might mean.

Structure is as used in the Munin source tree (browsable here:
L<http://munin-monitoring.org/browser/trunk/plugins>).  Those in
C<node.d/> are platform-independent, those in C<node.d.linux/> most
likely require Linux-specific functionality.

=head1 WARNING

Most of these are still works in progress, so unless explicitly noted
otherwise, breaking changes may occur at any time.  That may mean losing graph
history, or having to re-configure the node to avoid gaps.

=head1 PLUGINS

This is just a brief overview of available plugins.  The plugins should
(eventually) contain more detailed documentation in POD format.

=over 4

=item C<node.d/nagiostats_>

Statistics relating to Nagios performance.  Mostly works, should be fairly stable.


=item C<node.d.linux/cpuidle> (requires multigraph)

Monitor usage of CPU idle states.  Still very raw, both in terms of the code as
well as the usefulness of the graphs.


=back

=head1 INSTALLING

Wherever possible, they should work cleanly with C<munin-node-configure>.  See
individual plugins for specific caveats.

